version: '3.4'
services:
  selenium-initializer:
    build:
      context: .
      target: build
    # Runs test execution
    command: >
      sh -c "npm run webdriver:update;
             npm run start"
